<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.ruoyi</groupId>
        <artifactId>ruoyi</artifactId>
        <version>3.6.8</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>cloudwork-tenant</module>
        <module>cloudwork-project</module>
    </modules>

    <artifactId>cloudwork-services</artifactId>
    <packaging>pom</packaging>

    <description>CloudWork业务服务聚合模块</description>
</project>
